name: Metrics
on:
  schedule: [{ cron: "0 */6 * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics · overview
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kjodhpur
          template: classic
          base: header
          base_indepth: yes
          filename: metrics.overview.svg
          output_action: commit
          committer_message: "chore(metrics): update overview"
          config_timezone: America/Phoenix
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Metrics · languages
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kjodhpur
          template: classic
          base: ""
          filename: metrics.languages.svg
          output_action: commit
          committer_message: "chore(metrics): update languages"
          plugin_languages: yes
          plugin_languages_ignored: html, css, makefile, less, dockerfile, shell
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_other: yes
      - name: Metrics · activity
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kjodhpur
          template: classic
          base: ""
          filename: metrics.activity.svg
          output_action: commit
          committer_message: "chore(metrics): update activity"
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
      - name: Metrics · achievements
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kjodhpur
          template: classic
          base: ""
          filename: metrics.achievements.svg
          output_action: commit
          committer_message: "chore(metrics): update achievements"
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_limit: 6
          plugin_achievements_display: compact
      - name: Metrics · habits
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kjodhpur
          template: classic
          base: ""
          filename: metrics.habits.svg
          output_action: commit
          committer_message: "chore(metrics): update habits"
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
